### ISSUE TITLE
How to use with defaultProps and dynamic props

### ISSUE THREAD

**Issue by angeloashmore** [asyarb/babel-plugin-style-props#1]
How might this plugin support `defaultProps`? Since all props are transformed at build-time, I assume `defaultProps` are not available.

Consider the following example:

```jsx
const Input = props => (<input bg="red" {...props} />)
Input.defaultProps = { p: 1 }
```

At build-time, `input` would receive styles containing `background: red;` on the `css` prop, but nothing about `padding`.

At run-time, `input` would receive the `p` default prop, but since `input` is not a `styled-system`-enabled component, the `p` prop is ignored.

## Ideas

1. **Don't use defaultProps**: Recommend a convention of not using default props. Default props make sense when defining styled components but may not make sense when defining components using this plugin.

```jsx
// with defaultProps
const Input = styled.input`
  /* default styles */
`
Input.defaultProps = { bg: 'red' }

// without defaultProps
// since the babel plugin will automatically create a styled-component for us, there is not need to use defaultProps
const Input = ({ bg = 'red' }) => (
  <input
    bg={bg}
    css={`
      /* default styles */
    `}
  />
)
```

2. **Embed a styled-system-like runtime**: Provide a default run-time evaluator for non-static props. This could be a function always provided to the CSS prop that iterates over all props **not** already processed. So as props are provided at run-time that were not available at build-time, the component can still process the styles.

**Comment by asyarb** [comment]
I know we discussed this internally, but posting our conclusions here for record keeping:
---

I agree with the approach of recommending the convention of just not using `defaultProps`. Component composition and style prop can be achieved by just using function default parameters and spreading props over your "`system" components that are built with this plugin.

**Comment by asyarb** [comment]
I'll be adding the docs on the recommended convention for default props by tonight hopefully, and i'll close this when it's in.  👍🏼

**Comment by asyarb** [comment]
This has been documented with the latest release!
